sofia.base.folder=/data/pictures/sofia
sofia.base.image.folder=${sofia.base.folder}/images
sofia.base.assets.bgm.folder=${sofia.base.folder}/assets/bgm
sofia.base.archive.folder=${sofia.base.folder}/archive
