sofia.base.folder=./data
sofia.base.image.folder=./data/images
sofia.base.assets.bgm.folder=${sofia.base.folder}/assets/bgm
sofia.base.assets.decorations.folder=${sofia.base.folder}/assets/decorations
sofia.base.archive.folder=${sofia.base.folder}/archive